import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale, useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import "./globals.css";
import StoreProvider from "@/store/StoreProvider";
import { getUser } from "../actions";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const user = await getUser();
  const headersList = await headers();

  const pathname = headersList.get("x-pathname") || "";

  if (!user && pathname !== `/${locale}`) {
    return (
      <html lang={locale} suppressHydrationWarning>
        <body className={` antialiased`}>
          <StoreProvider user={null}>
            <NextIntlClientProvider>{children}</NextIntlClientProvider>
          </StoreProvider>
        </body>
      </html>
    );
  }
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={` antialiased`}>
        <StoreProvider user={user}>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
